# .config/kitty/kitty.conf
# Simon Hulse
# simonhulse@protonmail.com
# Last Edited: Wed 05 Feb 2025 01:30:06 PM EST

shell "/usr/bin/fish"

font_size 14.0
font_family family="Fira Code"
font_features FiraCode-Regular +liga +calt
font_features FiraCode-Bold +liga +calt

window_padding_width 8

scrollback_lines 10000

cursor_shape beam
strip_trailing_spaces smart
enable_audio_bell no
confirm_os_window_close 0

include current-theme.conf
