#!/usr/bin/csh

# utils/install-nmrpipe
# Simon Hulse
# simonhulse@protonmail.com
# Last Edited: Thu 27 Feb 2025 02:31:12 PM EST

set init_pwd = `pwd`

cd ~/progs

if ( -d nmrpipe ) then
    rm -r nmrpipe
endif

mkdir nmrpipe
cd nmrpipe

wget https://www.ibbr.umd.edu/nmrpipe/install.com
wget https://www.ibbr.umd.edu/nmrpipe/binval.com
wget https://www.ibbr.umd.edu/nmrpipe/NMRPipeX.tZ
wget https://www.ibbr.umd.edu/nmrpipe/s.tZ
wget https://www.ibbr.umd.edu/nmrpipe/dyn.tZ

wget https://www.ibbr.umd.edu/nmrpipe/talos_nmrPipe.tZ
wget https://www.ibbr.umd.edu/nmrpipe/plugin.smile.tZ

chmod a+r *.tZ *.Z *.tar
chmod a+rx *.com

./install.com

cd $init_pwd
